matrix_5into4=matrix(1:20,nrow = 5,ncol = 4)
print(matrix_5into4)
rowlabel=c("a","b","c")
collable=c("a","b","c")
matrix_3into3= matrix(1:9,nrow = 3, ncol = 3,byrow=TRUE,dimnames = list(rowlabel,collable))
print(matrix_3into3)
rowlabel1=c("a","b")
collable2=c("a","b")
matrix_2into2= matrix(1:4,nrow = 2, ncol = 2,byrow=FALSE,dimnames = list(rowlabel1,collable2))
print(matrix_2into2)