print("FIRST TEN ENGLISH LETTERS IN LOWERCASE")
first_ten_lc= head(letters,10)
print(first_ten_lc)
print("LAST TEN ENGLISH LETTERS IN UPPERCASE")
last_ten_uc= tail(LETTERS,10)
print(last_ten_uc)
print("UPPERCASE LETTERS FROM 22 TO 24")
uc_from_22to24=tail(LETTERS[22:24])
print(uc_from_22to24)