exam_data=data.frame(name=c('anastasia','dima','katherine','james','emily','michael','matthew','laura','kevin','jonas'),
                     score=c(12.5,9,16.5,12,9,20,14.5,13.5,8,19),
                     attempts=c(1,3,2,3,2,3,1,1,2,1),
                      qualify=c('yes','no','yes','no','no','yes','yes','no','no','yes'))
print(exam_data)
selected_rows_columns=exam_data[c(3,5),c(1,3)]
print(selected_rows_columns)
country=c("USA","USA","USA","USA","UK","USA","USA","India","USA","USA")
exam_data$Country=country
print(exam_data)
exam_data_new=data.frame(name=c('robert','sophia'),
                         score=c(10.5,9),
                         attempts=c(1,3),
                         qualify=c('yes','no'),
                         Country=c("usa","england")
)
exam_data_bind=rbind(exam_data,exam_data_new)
print(exam_data_bind)
sorted_exam_data=exam_data[order(exam_data$name,exam_data$score), ]
print(sorted_exam_data)
write.csv(exam_data,"examdataLOE.csv")
read_exam=read.csv("examdataLOE.csv")
print(read_exam)
