numeric_data=c(12,34,56)
character_data=c("hello","bye","see you")
logical_data=c(TRUE,FALSE,TRUE)
print(numeric_data)
print(typeof(numeric_data))
print(character_data)
print(typeof(character_data))
print(logical_data)
print(typeof(logical_data))